version: "3.9"
services:
  django:
    build: .
    container_name: jobintel_django
    command: python jobintel/manage.py runserver 0.0.0.0:8000 && python jobintel/manage.py migrate
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_worker:
    build: .
    container_name: jobintel_worker
    command: celery -A jobintel worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: jobintel_beat
    command: celery -A jobintel beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:6
    container_name: jobintel_redis
    ports:
      - "6379:6379"